# Generated by Django 5.0 on 2024-04-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
