# Generated by Django 5.0 on 2024-04-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngine', '0003_blogpost_slug'),
    ]

operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
]
