# Generated by Django 5.0 on 2024-04-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngine', '0006_glossary'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
