# Generated by Django 5.0 on 2024-05-01 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngine', '0009_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_end_subscription',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='date_subscribed',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
