# Generated by Django 5.0 on 2024-05-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngine', '0010_subscriber_date_end_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
